const programs=[['Strength & Conditioning','Build work capacity, power and durable strength.'],['Muscle Building','Progressive hypertrophy blocks with intelligent volume.'],['Fat Loss','Conditioning-led training built around sustainable output.'],['Functional Training','Move better. Lift better. Perform better.'],['Athletic Performance','Speed, power and explosive strength for athletes.'],['Personal Training','One-to-one coaching with measurable progression.']];
const trainers=[['Marcus Reed','STRENGTH · 9 YEARS','Former competitive powerlifter. Focused on strength systems and technical lifts.'],['Elena Cruz','PERFORMANCE · 7 YEARS','Performance coach blending conditioning, mobility and athletic output.'],['Darius Cole','HYPERTROPHY · 8 YEARS','Body-composition specialist with a data-first approach to training.']];
const testimonials=[['“The atmosphere makes you want to work harder. The coaching keeps you from wasting a session.”','ALEX M. · 14 MONTHS'],['“Three months in, my lifts are up and my conditioning is finally where I wanted it.”','JORDAN K. · PRO MEMBER'],['“It feels like a performance club, not a crowded commercial gym.”','SAMIRA R. · 2 YEARS']];
const plans=[['STARTER','$29',['Full gym access','Basic equipment','Locker access']],['PRO','$59',['24/7 access','All training zones','Group classes','Fitness assessment']],['ELITE','$99',['Everything in Pro','Personal trainer sessions','Nutrition guidance','Priority booking']]];
const facilities=[['STRENGTH FLOOR','Racks, calibrated plates, platforms and premium selectorized machines.'],['CARDIO ZONE','Performance treadmills, bikes, rowers and conditioning tools.'],['FUNCTIONAL AREA','Rig systems, sleds, kettlebells, cables and open training space.'],['RECOVERY ZONE','Quiet reset space with mobility equipment and guided recovery tools.'],['LOCKER ROOMS','Secure lockers, premium showers and post-session essentials.'],['PERSONAL TRAINING STUDIO','Private coaching environment for focused one-to-one work.']];
const schedule=[['MON','HIIT','Strength','Boxing','Mobility','Functional','—'],['TUE','Strength','Cross','HIIT','Boxing','Yoga','—'],['WED','Boxing','Strength','Functional','HIIT','Mobility','—'],['THU','Cross','HIIT','Strength','Yoga','Boxing','—'],['FRI','Strength','Functional','HIIT','Cross','Mobility','—']];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function render(){
 $('#programs').style.setProperty('--x','1');
 $('[data-programs]').innerHTML=programs.map((p,i)=>`<article class="program-card magnetic" data-index="${i}"><strong>${p[0]}</strong><span>${p[1]}</span></article>`).join('');
 $('[data-trainers]').innerHTML=trainers.map((t,i)=>`<article class="trainer-card magnetic"><div class="trainer-photo" aria-hidden="true"></div><div class="inner"><strong>${t[0]}</strong><small>${t[1]}</small><p>${t[2]}</p></div></article>`).join('');
 $('[data-testimonials]').innerHTML=testimonials.map(t=>`<article class="quote-card"><p>${t[0]}</p><strong>${t[1].split(' · ')[0]}</strong><span>${t[1].split(' · ')[1]}</span></article>`).join('');
 $('[data-plans]').innerHTML=plans.map((p,i)=>`<article class="plan ${i===1?'recommended':''}">${i===1?'<span class="badge">MOST POPULAR</span>':''}<h3>${p[0]}</h3><div class="price">${p[1]} <small>/ month</small></div><ul>${p[2].map(x=>`<li>＋ ${x}</li>`).join('')}</ul><a class="btn ${i===1?'btn-red':'btn-ghost'} magnetic" href="#contact">JOIN ${p[0]}</a></article>`).join('');
 $('[data-facilities]').innerHTML=facilities.map((f,i)=>`<article class="facility"><small class="eyebrow">0${i+1} · FACILITY</small><strong>${f[0]}</strong><p>${f[1]}</p></article>`).join('');
 $('[data-schedule]').innerHTML=`<div class="schedule-row head"><strong>DAY</strong>${['6 AM','8 AM','12 PM','5 PM','7 PM','9 PM'].map(x=>`<span>${x}</span>`).join('')}</div>`+schedule.map(r=>`<div class="schedule-row"><strong>${r[0]}</strong>${r.slice(1).map(x=>`<span>${x}</span>`).join('')}</div>`).join('');
}
function setupNav(){const nav=$('[data-nav]'),toggle=$('[data-menu-toggle]'),menu=$('[data-mobile-menu]'); addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>40),{passive:true}); toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close menu':'Open menu')}); menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')))}
function setupMotion(){if(!window.gsap||!window.ScrollTrigger)return;gsap.registerPlugin(ScrollTrigger);
 $$('.cinema').forEach((scene,idx)=>{const bg=scene.querySelector('.scene-bg');const copy=scene.querySelector('.scene-copy,.final-copy');const cards=scene.querySelectorAll('.program-card,.trainer-card,.quote-card,.plan,.stats-panel');gsap.fromTo(bg,{scale:1.08,xPercent:idx%2?-2:2},{scale:1.01,xPercent:idx%2?2:-2,ease:'none',scrollTrigger:{trigger:scene,start:'top bottom',end:'bottom top',scrub:true}});if(copy)gsap.fromTo(copy,{y:80,opacity:0},{y:0,opacity:1,ease:'none',scrollTrigger:{trigger:scene,start:'top 76%',end:'top 38%',scrub:true}});if(cards.length)gsap.fromTo(cards,{y:50,opacity:0,scale:.97},{y:0,opacity:1,scale:1,stagger:.08,ease:'power2.out',scrollTrigger:{trigger:scene,start:'top 58%',toggleActions:'play none none reverse'}})});
 $$('.content-section').forEach(sec=>{const head=sec.querySelector('.section-head');if(head)gsap.fromTo(head,{y:42,opacity:0},{y:0,opacity:1,duration:.7,scrollTrigger:{trigger:sec,start:'top 78%'}})});
}
function magnetic(){ $$('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{if(matchMedia('(pointer:fine)').matches){const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.12,y=(e.clientY-r.top-r.height/2)*.12;el.style.transform=`translate(${x}px,${y}px)`}});el.addEventListener('pointerleave',()=>el.style.transform='')}) }
function setupForm(){const form=$('[data-contact-form]');form.addEventListener('submit',e=>{e.preventDefault();$('[data-form-note]').textContent='Tour request captured. We’ll contact you to confirm a time.';form.reset()})}
render();setupNav();setupMotion();magnetic();setupForm();
